# Generated by Django 4.0.4 on 2022-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockeduser',
            name='user',
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
