# Generated by Django 4.0.4 on 2022-06-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
