# Generated by Django 4.0.4 on 2022-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
