# Generated by Django 4.0.4 on 2022-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='New', max_length=10),
        ),
    ]
