# Generated by Django 4.0.4 on 2022-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_order_method_orderproduct_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='method',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('COD', 'COD'), ('Razorpay', 'Razorpay')], max_length=15, null=True),
        ),
    ]
