# Generated by Django 4.0.4 on 2022-06-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_active',
        ),
    ]
