# Generated by Django 4.0.4 on 2022-06-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
