# Generated by Django 4.0.4 on 2022-06-10 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='reviews')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='reviews')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='reviews')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='reviews')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
