# Generated by Django 4.0.4 on 2022-06-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_reviews_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='image4',
        ),
    ]
