# Generated by Django 4.0.4 on 2022-06-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_discount_user_discountuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountuser',
            old_name='uesr',
            new_name='user',
        ),
    ]
