# Generated by Django 4.0.4 on 2022-06-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_uesr_discountuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountuser',
            name='discount',
        ),
    ]
