# Generated by Django 4.0.4 on 2022-06-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_discountcoupon_delete_discount_delete_discountuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='active_from',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
