# Generated by Django 4.0.4 on 2022-06-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_discountcoupon_active_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
