# Generated by Django 4.0.4 on 2022-06-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_discountcoupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
