# Generated by Django 4.0.4 on 2022-06-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_discountcoupon_active_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
