# Generated by Django 4.0.4 on 2022-06-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
